@startuml
skinparam monochrome true

participant Sensor as s
participant microROS as uros
participant ROS2 as ros


activate uros
activate ros
loop
    s -> uros: Range x
    activate s
end
    uros <-- ros: /tof/threshold [std_msgs/msg/Int32]\n'{data: y}'
    alt Object in range: x < y
        uros -> ros: /tof/trigger [std_msgs/msg/Bool]\n'{data: true}'
    else Object out of range: x >= y
        uros -> ros: /tof/trigger [std_msgs/msg/Bool]\n'{data: false}'
    end
    == Debug messages ==
    uros <-- ros: /tof/debug [std_msgs/msg/Bool]\n'{data: true}'
    activate uros
    loop
    uros -> ros: /tof/measure [std_msgs/msg/Int32]\n'{data: x}'
    end
    uros <-- ros: /tof/debug [std_msgs/msg/Bool]\n'{data: false}'
    deactivate uros
@enduml